// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibigbhemrdrokjgrkddp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaWdiaGVtcmRyb2tqZ3JrZGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDAzNDcsImV4cCI6MjA1NzM3NjM0N30.M_S9boEZG3vVx8uvfG25ghre0m0fTFCJ33yxHD2aSMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);